### ISSUE TITLE
SSL Certificate expired for inkplate.io

### ISSUE THREAD

**Issue by bbernhard** [e-radionicacom/Inkplate-documentation#1]
That's probably not the right place to put this one, but I was browsing your site (inkplate.io) and saw that your SSL certificate expired on October 18, 2020. At first I thought the project is already dead (due to the expired SSL certificate), but according to activity on github it seems pretty active. :)

**Comment by davidzovko** [comment]
Thanks on the report, fixed!

**Comment by bbernhard** [comment]
Unfortunately the issue still seems to exist

see: https://www.ssllabs.com/ssltest/analyze.html?d=inkplate.io

**Comment by davidzovko** [comment]
Thanks - fixed at last. Please report if an error is detected again.
