### ISSUE TITLE
Incorrect URL on www.crowdsupply.com

### ISSUE THREAD

**Issue by peterbozso** [e-radionicacom/Inkplate-documentation#11]
Hi!

First of all: cool product! Keep the good work up! :)

Secondly, on this page: https://www.crowdsupply.com/soldered/inkplate-10

In this text:

> And for the hardened ESP32 programmers out there, we also support ESP-IDF. Regardless, [our documentation](https://inkplate.readthedocs.io/en/latest/api-refrence.html) is here to help.

The URL is incorrect. The word "reference" is missing an "e" letter, so now it leads to this 404 page: https://inkplate.readthedocs.io/en/latest/api-refrence.html

Thanks,
Péter

**Comment by davidzovko** [comment]
Thanks, I've sent this to Crowd Supply and they'll fix it!
